name: 拉取镜像推送
env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.DOCKER_USERNAME }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

on:

  workflow_dispatch:

    inputs:

      IMAGE_NAME:

        description: '原镜像名称:版本'

        required: true

        default: 'rancher/rancher-agent:v2.5.7'

      NEW_NAME:

        description: '同步后镜像名称:版本'

        required: true

        default: 'rancher-agent:v2.5.7'
      ARCH:

        description: '系统架构'

        required: true

        default: 'x86_64'

        type: choice

        options:

          - amd64

          - arm64

          - arm/v7

          - arm/v6

          - 386

          - s390x

          - ppc64le

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: 登录到 Docker 仓库
		uses: docker/setup-buildx-action@v3
        id: login

        run: docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

        continue-on-error: true

      - name: 检查 Docker 登录成功
		uses: docker/setup-buildx-action@v3
        if: ${{ steps.login.outcome == 'success' }}

        run: echo "Docker 登录成功"

      - name: 检查 Docker 登录失败
		uses: docker/setup-buildx-action@v3
        if: ${{ steps.login.outcome != 'success' }}

        run: echo "Docker 登录失败"
		
      - name: 拉取、标记并推送 Docker 镜像
		uses: docker/setup-buildx-action@v3
        id: pull_tag_push

        run: |

          docker pull --platform ${{ github.event.inputs.ARCH }} ${{ github.event.inputs.IMAGE_NAME }}

          docker tag ${{ github.event.inputs.IMAGE_NAME }} $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/${{ github.event.inputs.NEW_NAME }}

          docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/${{ github.event.inputs.NEW_NAME }}

        continue-on-error: true

      - name: 检查镜像推送成功
		uses: docker/setup-buildx-action@v3
        if: ${{ steps.pull_tag_push.outcome == 'success' }}

        run: echo "Docker 镜像推送成功"

      - name: 检查镜像推送失败
		uses: docker/setup-buildx-action@v3
        if: ${{ steps.pull_tag_push.outcome != 'success' }}

        run: echo "Docker 镜像推送失败"
