name: GitHub to Alibaba Cloud Container Registry
env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.DOCKER_USERNAME }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  IMAGE_NAME: "rancher/rancher-agent:v2.5.7"
  NEW_NAME: "rancher-agent:v2.5.7"
  ARCH: "x86_64" 
on:
  push:
    branches: [ main ]
 
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
   
    - name: Log in to Alibaba Cloud Container Registry
      run: |
        echo "仓库地址$ALIYUN_REGISTRY--镜像名称$IMAGE_NAME" | docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY"
    - name: pull Docker Image
      run: pull --platform $ARCH  $IMAGE_NAME .
    - name: docker tag
      run: 	docker tag $IMAGE_NAME $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$NEW_NAME
    - name: Push Docker Image
      run: docker push ${{ secrets.ALIYUN_CR_REGISTRY }}/your-image-name:latest
